/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Inscripcion;
import Persistencia.InscripcionData;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cisco
 */
public class vistaInscripciones extends javax.swing.JInternalFrame {

    private InscripcionData repo = new InscripcionData();
    private List<Inscripcion> lista;

    /**
     * Creates new form vistaInscripciones
     */
    public vistaInscripciones() {
        initComponents();
        this.setTitle("Inscripciones");
        lista = repo.obtenerInscripciones();
        llenarTabla(lista);

    }

    private void doNothing() {
        var tm = jTable1.getModel();
        var x = jTable1.getSelectedRow();
        var y = 0;
        Inscripcion i = (Inscripcion) tm.getValueAt(x, y);
        repo.borrarInscripcionMateriaAlumno(i.getIdInscripcion());
        lista = repo.obtenerInscripciones();
        llenarTabla(lista);
        filtrar();
    }

    private void llenarTabla(List<Inscripcion> inscripciones) {
        var tm = new DefaultTableModel(new String[]{
            "id", "Alumno", "Materia", "Nota"}, 0);

        inscripciones.forEach(inscripcion -> {
            tm.addRow(new Object[]{
                inscripcion,
                inscripcion.getAlumno(),
                inscripcion.getMateria(),
                inscripcion.getNota(),});
        });
        jTable1.setModel(tm);
    }

    private void filtrar() {
        var pattern = jTextField1.getText().toLowerCase();

        if (pattern.isBlank()) {
            llenarTabla(lista);
            return;
        }

        llenarTabla(lista.stream()
                .filter(i -> {
                    var a = i.getAlumno();
                    var m = i.getMateria();
                    var cString = (String.valueOf(a.getDni())
                            + a.getNombre()
                            + a.getApellido()
                            + a.getDni()
                            + m.getNombre_materia())
                            .toLowerCase();
                    return cString.contains(pattern);
                }).toList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setResizable(true);
        setName("Inscripciones"); // NOI18N

        jTextField1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextField1PropertyChange(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setText("Filtrar");

        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextField1PropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1PropertyChange

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        filtrar();
    }//GEN-LAST:event_jTextField1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
